language: python
node_js: "stable"
cache: pip
python:  3.6

before_install:
  - npm install -g npm@latest

install:
  - npm install -g htmlhint
  - npm install -g jshint
  - npm install -g stylelint
  - pip install pylinkvalidator
  - pip install -U https://github.com/openwisp/openwisp-utils/tarball/master#egg=openwisp_utils

script:
  - ./run-qa-checks
